
export const metadata = {
    title: "Publications",
    description: '',
}

export default function Publications() {
    return (
        <>
            <h1>Publications</h1>
            <p>Click here for my <a href="https://scholar.google.com.au/citations?user=ynWS968AAAAJ&amp;hl=en">Google Scholar</a> profile</p>
            <p>Publications: 3859 citations, h-index = 37, i10-index = 69; Google Scholar on 16 August 2022</p>
            <p>Summary: 13 book chapters, 107 journal articles, 8 conference proceedings, 21 editorial commentaries/perspectives</p>
            <p><strong><u>Chapters in Books</u></strong>:</p>
            <p>120) <strong>Rummer, J.L.,</strong> <u>Illing, B</u>. (2022) Coral Reef Fishes in a Multi-Stressor World, Chapter 7 in Fangue, N.A., Farrell, A.P., and Cooke, S.J. (eds) Fish Physiology, Volume 39B, Elsevier. (<em>in press</em>)</p>
            <p>119) <strong>Rummer, J.L.,</strong> <u>Bouyoucos, I.A.</u>, <u>Wheeler, C.</u>, Santos, C.P., Rosa, R. (2022). Climate Change and Sharks, Chapter 25 in Carrier, J.C., Simpfendorfer, C.A., Heithaus, M.R., and Yopak, K.E. (eds) Biology of Sharks and their Relatives, Third Edition. CRC Press. 840pp. <a href="https://doi.org/10.1201/9781003262190">https://doi.org/10.1201/9781003262190</a></p>
            <p>118) Cooke, S.J., Madliger, C.L., Bergman, J.N., Nguyen, V.M., Landsman, S.J., Love, O.P., <strong>Rummer, J.L.</strong>, Franklin, C.E. (2020). Optimism and opportunities for conservation physiology in the Anthropocene: a synthesis and conclusions, Chapter 19 in Cooke, S.J., Madliger, C.L., Love, O.P., and Franklin, C.E. (eds) Conservation physiology: Integrating physiology into animal conservation and management. Oxford University Press. ISBN: 9780198843627. pp. 319-329. <a href="https://doi.org/10.1093/oso/9780198843610.003.0019">https://doi.org/10.1093/oso/9780198843610.003.0019</a></p>
            <p>117) <u>Laubenstein, T.D.</u> and <strong>Rummer, J.L.</strong> (2020). Communication in conservation physiology: linking diverse stakeholders, promoting public engagement, and encouraging application, Chapter 18 in Cooke, S.J., Madliger, C.L., Love, O.P., and Franklin, C.E. (eds) Conservation physiology: Integrating physiology into animal conservation and management. Oxford University Press. ISBN: 9780198843627. pp. 303-317. <a href="https://doi.org/10.1093/oso/9780198843610.003.0018">https://doi.org/10.1093/oso/9780198843610.003.0018</a> </p>
            <p>116) <u>Bouyoucos</u><u>, I.A.</u> and <strong>Rummer, J.L.</strong> (2020). Improving &ldquo;shark park&rdquo; protections under threat from climate change using the conservation physiology tool box, Chapter 11 in Cooke, S.J., Madliger, C.L., Love, O.P., and Franklin, C.E. (eds) Conservation physiology: Integrating physiology into animal conservation and management. Oxford University Press. ISBN: 9780198843627. pp. 185-204. <a href="https://doi.org/10.1093/oso/9780198843610.003.0011">https://doi.org/10.1093/oso/9780198843610.003.0011</a></p>
            <p>115) <strong>Rummer, J.L.</strong> and Brauner, C.J. (2020) Gas Exchange, Chapter 3 in Currie, S. and Evans, D.H (eds) The Physiology of Fishes, 5th&nbsp;Edition. CRC Press/Taylor and Francis Group. pp. 33-45. doi: <a href="https://doi.org/10.1201/9781003036401" target="_blank">https://doi.org/10.1201/9781003036401</a></p>
            <p>114) Munday, P.L., <strong>Rummer, J.L.</strong>, Baumann, H. (2019) Adaptation and evolutionary responses to high CO2, in Grosell, M., Munday, P.L., Farrell, A.P., and Brauner, C.J. (eds) Fish Physiology, Volume 37, Elsevier. ISSN 1546-5098, pp. 369-395. doi: https://doi.org/10.1016/bs.fp.2019.07.006</p>
            <p>113) Brauner, C.J., Harter, T.S., <strong>Rummer, J.L. </strong>(2017) Gas Transport and Exchange: Interaction Between O2 and CO2 Exchange, In Reference Module in Life Sciences, Elsevier, ISBN: 978-0-12-809633-8, doi: 10.1016/B978-0-12-809633-8.03114-9</p>
            <p>112)<strong> Rummer, J.L.</strong>, Isom, L.L. (2015) Communicating Science. In Pritchard, P.A. &amp; Grant, C. (eds.) Success Strategies from Women in STEM: A Portable Mentor, 2nd edition. Elsevier. pp. 201-253.</p>
            <p>111) Darling, E.<strong>, Rummer, J.L.</strong> (2015) Strategically Using Social Media. In Pritchard, P.A. &amp; Grant, C. (eds.) Success Strategies from Women in STEM: A Portable Mentor, 2nd edition. Elsevier. pp. 255-296.</p>
            <p>110)<strong> Rummer, J.L.</strong>, (2015) Networking. In Pritchard, P.A. &amp; Grant, C. (eds.) Success Strategies from Women in STEM: A Portable Mentor, 2nd edition. Elsevier. pp. 23-60.</p>
            <p>109) Brauner, C.J., <strong>Rummer, J.L. </strong>(2011) Gas Transport and Exchange: Interaction Between O2 and CO2 Exchange. In: Farrell A.P., (ed.), Encyclopedia of Fish Physiology: From Genome to Environment, volume 2, pp. 916&ndash;920. San Diego: Academic Press. doi:10.1016/B978-0-1237-4553-8.00115-5</p>
            <p>108) <strong>Rummer, J.L.</strong> (2007) Interacting factors affecting release mortality in red snapper with an emphasis on catastrophic decompression and swim bladder form and function. pp.123-144 <em>in</em> W.F. Patterson, III, J.H. Cowan, Jr., G.R. Fitzhugh, &amp; D.L. Nieland, eds. Red Snapper Ecology &amp; Fisheries in the U.S. Gulf of Mexico, American Fisheries Society Symp. 60, Bethesda, Maryland. IF: n/a, Citations: 34</p>
            <p><strong><u>Journal Articles</u></strong><strong>:<br /></strong><strong>(Average Impact Factor: 4.993, Median Impact Factor: 3.312)</strong><br />&nbsp;<br /><u>Note</u>: underscored names are postgraduate students or post-docs that I supervise or have supervised.<br />&nbsp;<br />107) <u>Wheeler, C.R</u>., Lang, B.J., Mandelman, J.W., <strong>Rummer,</strong> <strong>J.L.</strong> (2022) The upper thermal limit of a tropical elasmobranch is conserved across life history stages and body sizes. <strong><em>Conservation Physiology</em></strong>. (in press).<br />IF: 3.079, Citations: n/a, Altmetric: n/a</p>
            <p>106) <u>Trujillo, J.E.</u>, <u>Bouyoucos, I.</u>, Rayment, W.J., Domenici, P., Planes, S., <strong>Rummer, J.L.</strong>, Allan, B.J.M. (2022). Escape response kinematics in two species of tropical sharks: short escape latencies and high turning performance. <strong><em>Journal of Experimental Biology</em></strong> (in press).<br />IF: 3.312, Citations: n/a, Altmetric: n/a</p>
            <p>105) Porter, M.E., Hernandez, A.V., <u>Gervais, C.R.</u>, <strong>Rummer, J.L. </strong>(2022) Aquatic walking and swimming kinematics of neonate and juvenile epaulette sharks. <strong><em>Integrative and Comparative Biology</em></strong><em>. </em>(in press)<br />IF: 3.326, Citations: n/a, Altmetric: n/a</p>
            <p>104) <u>Wheeler, C.R.</u>, Kneebone, J., <u>Heinrich, D.</u>, Strugnell, J.M., Mandelman, J.W., <strong>Rummer, J.L. </strong>(2022). Diel rhythm and thermal independence of metabolic rate in a benthic shark. <strong><em>Journal of Biological Rhythms</em></strong><em>. </em><a href="https://doi.org/10.1177/07487304221107843">https://doi.org/10.1177/07487304221107843</a><br />IF: 3.649, Citations: 0, Altmetric: 4</p>
            <p>103) Ferreira, P., Kwan, G.T., Haldorson, S., <strong>Rummer, J.L.</strong>, Tashiro, F., Castro, L.F.C., Tresguerres, M., Wilson, J.M. (2022). A multi-tasking stomach: functional co-existence of acid-peptic digestion and defensive body inflation in three distantly related vertebrate lineages. <strong><em>Biology Letters</em></strong> <a href="https://doi.org/10.1098/rsbl.2021.0583">https://doi.org/10.1098/rsbl.2021.0583</a><br />IF: 3.703, Citations: n/a, Altmetric: n/a</p>
            <p>102) Kang, J., Nagelkerken, I., <strong>Rummer, J.L.</strong>, Rodolfo-Metalpa, R., Munday, P.L., Ravasi, T., Schunter, C. (2022). Rapid evolution fuels transcriptional plasticity to ocean acidification. <strong><em>Global Change Biology</em></strong>. <a href="https://doi.org/10.1111/gcb.16119">https://doi.org/10.1111/gcb.16119</a><br />IF: 10.863, Citations: n/a, Altmetric: n/a</p>
            <p>101) <u>Bouyoucos, I.A.</u>, Simpfendorfer, C.A., Planes, S., <u>Schwieterman, G.D.</u>, <u>Weideli, O.C.</u>, <strong>Rummer, J.L.</strong> (2022). Thermally insensitive physiological performance allows neonatal sharks to use coastal habitats as nursery areas. <strong><em>Marine Ecology Progress Series </em></strong>682:137&ndash;152. <a href="https://doi.org/10.3354/meps13941">https://doi.org/10.3354/meps13941</a><br />IF: 2.824, Citations: n/a, Altmetric: 25<br />*this research was highlighted in the media and via press releases</p>
            <p>100) Shu, J.J., Heuer, R.M., <u>Hannan, K.D.</u>, Stieglitz, J.D., Benetti, D.D., <strong>Rummer, J.L.</strong>, Grosell, M., Brauner, C.J. (2022). Enhanced oxygen unloading in two marine percomorph teleosts. <strong><em>Comparative</em></strong> <strong><em>Biochemistry and Physiology Part A: Molecular &amp; Integrative Physiology</em></strong> 264:111101. <a href="https://doi.org/10.1016/j.cbpa.2021.111101">https://doi.org/10.1016/j.cbpa.2021.111101</a><br />IF: 2.320, Citations: n/a, Altmetric: 3</p>
            <p>99) Gr&eacute;goire, M., Gar&ccedil;on, V., Garcia, H., Breitburg, D., Isensee, K., Oschlies, A., Telszewski, M., Barth, A., Bittig, H.C., Carstensen, J., Carval, T., Chai, F., Chavez, F., Conley, D., Coppola, L., Crowe, S., Currie, K., Dai, M., Deflandre, B., Dewitte, B., Diaz, R., Garcia-Robledo, E., Gilbert, D., Giorgetti, A., Glud, R., Gutierrez, D., Hosoda, S., Ishii, M., Jacinto, G., Langdon, C., Lauvset, S.K., Levin, L.A., Limburg, K.E., Mehrtens, H., Montes, I., Naqvi, W., Paulmier, A., Pfeil, B., Pitcher, G., Pouliquen, S., Rabalais, N., Rabouille, C., Recape, V., Roman, M., Rose, K., Rudnick, D., <strong>Rummer, J.,</strong> Schmechtig, C., Schmidtko, S., Seibel, B., Slomp, C., Sumalia, U.R., Tanhua, T., Thierry, V., Uchida, H., Wanninkhof, R., Yasuhara, M. (2021). A global ocean oxygen database and atlas for assessing and predicting deoxygenation and ocean health in the open and coastal ocean. <strong><em>Frontiers in Marine Science</em></strong> <a href="https://doi.org/10.3389/fmars.2021.724913">https://doi.org/10.3389/fmars.2021.724913</a><br />IF: 4.44, Citations: n/a, Altmetric: 88<br />*this research was highlighted in the media and via press releases</p>
            <p>98) Pereira&nbsp;Santos, C., Sampaio, E., Pereira, B., Pegado, M.R., Borges, F.O., <u>Wheeler, C.</u>, <u>Bouyoucos, I.</u>, <strong>Rummer, J.</strong>, Fraz&atilde;o&nbsp;Santos, C., Rosa, R. (2021). Elasmobranch responses to experimental warming, acidification, and oxygen loss - a meta-analysis. <strong><em>Frontiers in Marine Science</em></strong>. <a href="https://doi.org/10.3389/fmars.2021.735377">https://doi.org/10.3389/fmars.2021.735377</a> <br />IF: 5.247, Citations: 1, Altmetric: 39</p>
            <p>97) <u>Dubuc, A.</u>, Collins, G.M., Coleman, L., Waltham, N.J., <strong>Rummer, J.L.</strong>, Sheaves, M. (2021). Association between physiological performance and short temporal changes in habitat utilisation modulated by environmental factors. <strong><em>Marine Environmental Research</em></strong> 170:105448. <a href="https://doi.org/10.1016/j.marenvres.2021.105448">https://doi.org/10.1016/j.marenvres.2021.105448</a>&nbsp;<br />IF: 3.130, Citations: n/a, Altmetric: n/a</p>
            <p>96) <u>Schoen, A.N</u>, <u>Bouyoucos, I.A.</u>, Anderson, W.G., Wheaton, C.J., Planes, S., Mylniczenko, N.D., <strong>Rummer, J.L.</strong> (2021). Simulated heatwave and fishing stressors alter corticosteroid and energy balance in neonate blacktip reef sharks, <em>Carcharhinus melanopterus</em>.<strong><em> Conservation Physiology</em></strong> 9:coab067. <a href="https://doi.org/10.1093/conphys/coab067">https://doi.org/10.1093/conphys/coab067</a><br />IF: 3.079, Citations: n/a, Altmetric: n/a</p>
            <p>95) <u>Schwieterman, G.D.</u>, <strong>Rummer, J.L.</strong>, <u>Bouyoucos, I.A.</u>, Bushnell, P.G., Brill, R.W. (2021) A lack of red blood cell swelling in five elasmobranch fishes following air exposure and exhaustive exercise. <strong><em>Comparative Biochemistry and Physiology Part A: </em></strong><strong><em>Molecular and Integrative Physiology</em></strong> 258:110978. <a href="https://doi.org/10.1016/j.cbpa.2021.110978">https://doi.org/10.1016/j.cbpa.2021.110978</a> <br />IF: 2.888, Citations: 1, Altmetric: 13</p>
            <p>94) Madliger, C.L., Franklin, C.E., Chown, S.L., Fuller, A., Hultine, K.R., Costantini, D., Hopkins, W.A., Peck, M.A., <strong>Rummer, J.L.</strong>, Sack, L., Willis, C.K.R., Cooke, S.J. (2021) The second warning to humanity: Contributions and solutions from conservation physiology. <strong><em>Conservation Physiology</em></strong> 9, coab038. <a href="https://doi.org/10.1093/conphys/coab038">https://doi.org/10.1093/conphys/coab038</a><br />IF: 3.079, Citations: n/a, Altmetric: n/a</p>
            <p>93) <u>Prescott, L.A.</u>, Regish, A.M., McMahon, S. J., McCormick, S. D., <strong>Rummer, J.L.</strong> (2021) Rapid embryonic development supports the early onset of gill functions in two coral reef damselfishes. <strong><em>Journal of Experimental Biology</em></strong> 224:jeb242364. <a href="https://doi.org/10.1242/jeb.242364">https://doi.org/10.1242/jeb.242364</a><br />IF: 3.312, Citations: 0, Altmetric: 3</p>
            <p>92) <u>Downie, A.T.</u>, Phelps, C.M., <strong>Rummer, J.L.</strong>, Chivers, D.P., Ferrari, M.C.O., McCormick, M.I. (2021) Exposure to degraded&nbsp;coral&nbsp;habitat depresses oxygen uptake rate during exercise of a juvenile reef fish. <strong><em>Coral Reefs</em></strong> doi: <a href="https://doi.org/10.1007/s00338-021-02113-x">https://doi.org/10.1007/s00338-021-02113-x</a><br />IF: 3.902, Citations: n/a, Altmetric: 26<br />*this research was highlighted in the media and via press releases</p>
            <p>91) <u>Bouyoucos, I.A.</u>, <u>Trujillo, J.E.</u>, <u>Weideli, O.C.</u>, Nakamura, N., Mourier, J., Planes, S., Simpfendorfer, C.A., Rummer, J.L. (2021). Investigating links between thermal tolerance and oxygen supply capacity in shark neonates from a hyperoxic tropical environment <em>Science of the Total Environment</em> 782:146854. doi:10.1016/j.scitotenv.2021.146854<em>.</em>IF: 7.963, Citations: n/a, Altmetric: 26</p>
            <p>90) <u>Downie</u><u>, A.T.</u>, Leis, J.M., Cowman, P.F., McCormick, M.I., <strong>Rummer, J.L.</strong> (2021). Habitat association may influence swimming performance in marine teleost larvae. <strong><em>Fish and Fisheries</em></strong> doi: <a href="https://doi.org/10.1111/faf.12580">https://doi.org/10.1111/faf.12580</a>&nbsp;<br />IF: 6.785, Citations: n/a, Altmetric: n/a<br />*this research was highlighted in the media and via press releases</p>
            <p>89) Cooke, S.J., Bergman, J.N., Madliger, C.L., Cramp, R.L., Beardall, J., Burness, G.P., Clark, T.D., Dantzer, B., de la Barrera, E., Fangue, N.A., Franklin, C.E., Fuller, A., Hawkes, L.A., Hultine, K.R., Hunt, K.E., Love, O.P., MacMillan, H.A., Mandelman, J.W., Mark, F.C., Martin, L.B., Newman, A.E.M., Nicotra, A.B., Raby, G.D., Robinson, S.A., Ropert-Coudert, Y., <strong>Rummer</strong>, <strong>J.L., </strong>Seebacher, F., Todgham, A.E., Tomlinson, S., and Chown, S.L. (2021).&nbsp;One hundred research questions in conservation physiology for generating actionable evidence to inform conservation policy and practice.&nbsp;<strong><em>Conservation Physiology</em></strong>. 9, coab009.&nbsp;<a href="https://doi.org/10.1093/conphys/coab009">https://doi.org/10.1093/conphys/coab009</a>.<br />IF: 3.079, Citations: n/a, Altmetric: 63</p>
            <p>88) <u>Wheeler, C.R.</u>, <strong>Rummer, J.L.</strong>, Bailey, B., Lockwood, J., Vance, S. Mandelman, J.W. (2021) Future thermal regimes for epaulette sharks (<em>Hemiscyllium ocellatum</em>): growth and metabolic performance cease to be optimal. <strong><em>Scientific Reports</em></strong> 11(1), 1-12. doi: <a href="https://doi.org/10.1038/s41598-020-79953-0">https://doi.org/10.1038/s41598-020-79953-0</a><br />IF: 4.996, Citations: 7, Altmetric: 1348<br />*this research was highlighted in the media and via press releases</p>
            <p>87) <u>Hannan, K.D.</u>, McMahon, S., Munday, P.L., <strong>Rummer, J.L.</strong> (2021) Contrasting effects of constant and fluctuating pCO2 conditions on the exercise physiology of coral reef fishes. <strong><em>Marine Environmental Research</em></strong> 163, 105224. doi: <a href="https://doi.org/10.1016/j.marenvres.2020.105224" target="_blank">https://doi.org/10.1016/j.marenvres.2020.105224</a><br />IF: 3.130, Citations: n/a, Altmetric: 11</p>
            <p>86) <u>Illing, B.</u>, Severati, A., Hochen, J., Boyd, P., Raison, P., Mather, R., <u>Downie, A.T.</u>, <strong>Rummer, J.L.</strong>, Kroon, F.J., Humphrey, C. (2021). Automated flow control of a multi-lane swimming chamber for small fishes indicates species-specific sensitivity to experimental protocols. <strong><em>Conservation Physiology </em></strong>9(1),coaa131. doi: <a href="https://doi.org/10.1093/conphys/coaa131">https://doi.org/10.1093/conphys/coaa131</a> <br />IF: 3.079, Citations: n/a, Altmetric: 15</p>
            <p>85) <u>Nay, T.J.</u>, Johansen, J.L., <strong>Rummer, J.L</strong>, Steffensen, J.F., Hoey, A.S. (2021) Species interactions alter the selection of thermal environment in a coral reef fish. <strong><em>Oecologia</em></strong>. doi: <a href="https://doi.org/10.1007/s00442-021-04942-7">https://doi.org/10.1007/s00442-021-04942-7</a> .<br />IF: 3.225, Citations: n/a, Altmetric: n/a</p>
            <p>84) <u>Heinrich, D.</u>, Dhellemmes, F., Guttridge, T.L., Smukall, M., Brown, C., <strong>Rummer, J.L.</strong>, Gruber, S., Huveneers, C. (2021) <a>Short-term impacts of daily feeding on the residency, distribution, and energy expenditure of sharks</a>. <strong><em>Animal Behaviour</em></strong> 172, 55-71. <a href="https://doi.org/10.1016/j.anbehav.2020.12.002">https://doi.org/10.1016/j.anbehav.2020.12.002</a><br />IF: 2.844, Citations: 1, Altmetric: 22</p>
            <p>83) Salmer&ograve;n, C., Harter, T.S., Kwan, G.T., Roa, J.N., Blair, S.D., <strong>Rummer, J.L.</strong>, Shiels, H.A., Goss, G.G., Wilson, R.W., Tresguerres, M. (2021) Molecular and biochemical characterization of the bicarbonate-sensing soluble adenylyl cyclase from a bony fish, the rainbow trout <em>Oncorhynchus mykiss</em>. <strong><em>Interface Focus</em></strong> <strong>11:</strong>20200026. doi:<a href="https://doi.org/10.1098/rsfs.2020.0026">http://doi.org/10.1098/rsfs.2020.0026</a><br />IF: 3.906, Citations: 3, Altmetric: 4</p>
            <p>82) <u>Gervais, C.R.</u>, Huveneers, C., <strong>Rummer, J.L.</strong>, Brown, C. (2021) Population variation in the thermal response to climate change reveals differing sensitivity in a benthic shark. <strong><em>Global Change Biology</em></strong> 27(1), 108-120. doi: <a href="https://doi.org/10.1111/gcb.15422">https://doi.org/10.1111/gcb.15422</a><br />IF: 10.863, Citations: n/a, Altmetric: 99<br />*this research was highlighted in the media and via press releases</p>
            <p>81) Johansen, J.L., Nadler, L.E., <u>Habary, A.</u>, <u>Bowden, A.J.</u>, <strong>Rummer, J.L.</strong> (2021) Thermal acclimation of tropical reef fishes to global heat waves. <strong><em>eLife</em></strong> 2021;10:e59162&nbsp;doi:&nbsp;<a href="https://doi.org/10.7554/eLife.59162">10.7554/elife.59162</a>.<br />IF: 8.140, Citations: n/a, Altmetric: 111<br />*this research was highlighted in the media and via press releases</p>
            <p>80) <u>Nay, T.J.</u>, Longbottom, R.J., <u>Gervais, C.R.</u>, Johansen, J.L., Steffensen, J.F., <strong>Rummer, J.L.</strong>, Hoey, A.S. (2020) Regulate or tolerate: Thermal strategy of a coral reef flat resident, the epaulette shark, <em>Hemiscyllium ocellatum</em>. <strong><em>Journal of Fish Biology</em></strong> doi: <a href="https://doi.org/10.1111/jfb.14616">https://doi.org/10.1111/jfb.14616</a><br />IF: 2.504, Citations: 4, Altmetric: 1</p>
            <p>79) <u>Nay, T.J.</u>, Johansen, J.L., <strong>Rummer</strong><strong>, J.L.</strong>, Steffensen, J.F., Pratchett, M.S., Hoey, A.S. (2020) Habitat complexity influences selection of thermal environment in a common coral reef fish. <strong><em>Conservation Physiology</em></strong> 8(1), coaa070 <a href="https://doi.org/10.1093/conphys/coaa070">https://doi.org/10.1093/conphys/coaa070</a><br />IF: 3.079, Citations: 6, Altmetric: 42</p>
            <p>78) Allan, B., Illing, B. Fakan, E.P., Narvaez, P., Grutter, A., Sikkel, P., McClure, E. <strong>Rummer, J.L.</strong>, McCormick, M.I. (2020) Parasite infection directly impacts escape response and stress levels in fish. <strong><em>Journal of Experimental Biology</em></strong> 223 (16): jeb230904 <a href="https://doi.org/10.1242/jeb.230904">https://doi.org/10.1242/jeb.230904</a> .<br />IF: 3.312, Citations: 0, Altmetric: n/a</p>
            <p>77) <u>Bouyoucos, I.A.</u>, Watson, S-A., Planes, S., Simpfendorfer, C.A., <u>Schwieterman, G.D.</u>, Whitney, N.M., <strong>Rummer, J.L.</strong> (2020) The power struggle: assessing interacting global change stressors via experimental studies on sharks. <strong><em>Scientific</em></strong> <strong><em>Reports</em></strong>. 10(1), 1-12. doi: <a href="https://doi.org/10.1038/s41598-020-76966-7">https://doi.org/10.1038/s41598-020-76966-7</a><br />IF: 4.379, Citations: n/a, Altmetric: 45</p>
            <p>76) Bouyoucos, I.A., Morrison, P., Weideli, O., Jacquesson, E., Planes, S., Simpfendorer, C., Brauner, C.J., Rummer, J.L. Thermal tolerance and hypoxia tolerance are associated in blacktip reef shark (<em>Carcharhinus melanopterus</em>) neonates. <strong><em>Journal of Experimental Biology</em></strong> 223(14), jeb221937. <a href="https://doi.org/10.1242/jeb.221937">https://doi.org/10.1242/jeb.221937</a><br />IF: 3.312, Citations: 0, Altmetric: n/a<br />*this research was highlighted in the media and via press releases</p>
            <p>75) <u>Hannan, K.D.</u>, Munday, P.L., <strong>Rummer, J.L. </strong>(2020) The effects of constant and fluctuating elevated <em>p</em>CO2 levels on oxygen uptake rates of coral reef fishes. <strong><em>Science of the Total Environment</em></strong> 741, 140334. doi: <a href="https://doi.org/10.1016/j.scitotenv.2020.140334" target="_blank">https://doi.org/10.1016/j.scitotenv.2020.140334</a><br />IF: 7.963, Citations: 1, Altmetric: 20</p>
            <p>74) <u>Bouyoucos, I.A.</u>, Romain, M., Azoulai, L., Eustache, K., Mourier, J., <strong>Rummer, J.L.</strong>, Planes, S. (2020) Home range of newborn blacktip reef sharks (<em>Carcharhinus melanopterus</em>), as estimated using mark-recapture and acoustic telemetry. <strong><em>Coral Reefs </em></strong>39, 1209-1214. doi: <a href="https://doi.org/10.1007/s00338-020-01965-z">https://doi.org/10.1007/s00338-020-01965-z</a><br />IF: 3.902, Citations: 3, Altmetric: 47</p>
            <p>73) <u>Hannan, K.D</u>., Miller, G.M., Watson, S-A., <strong>Rummer, J.L.</strong>, Fabricius, K., Munday, P.L. (2020) Diel <em>p</em>CO2 variation among coral reef sites and microhabitats at Lizard Island, Great Barrier Reef. <strong><em>Coral Reefs </em></strong>39(5), 1391-1406. doi: <a href="https://doi.org/10.1007/s00338-020-01973-z">https://doi.org/10.1007/s00338-020-01973-z</a><br />IF: 3.902, Citations: 3, Altmetric: 29</p>
            <p>72) <strong>Rummer, J.L.</strong>, <u>Bouyoucos, I.A.</u>, Mourier, J., Nakamura, N., Planes, S. (2020) Responses of a coral reef shark acutely exposed to ocean acidification conditions. <strong><em>Coral Reefs </em></strong>39(5), 1215-1220. <a href="https://doi.org/10.1007/s00338-020-01972-0">https://doi.org/10.1007/s00338-020-01972-0</a> <br />IF: 3.902, Citations: 1, Altmetric: 42</p>
            <p>71) <u>Wheeler, C.R.</u>, <u>Gervais, C.R.</u>, <u>Johnson, M.S.</u>, Vance, S., Rosa, R., Mandelman, J.W., <strong>Rummer, J.L. </strong>(2020) Anthropogenic stressors influence reproduction and development in elasmobranch fishes. <strong><em>Reviews in Fish Biology and Fisheries </em></strong>30, 373-386. doi: <a href="https://doi.org/10.1007/s11160-020-09604-0">https://doi.org/10.1007/s11160-020-09604-0</a><br />IF: 6.845, Citations: 17, Altmetric: 38</p>
            <p>70) <u>Illing, B.</u>, <u>Downie, A.T.</u>, <u>Beghin, M.</u>, <strong>Rummer, J.L.</strong> (2020) Critical thermal maxima of early life stages of three tropical fishes: effects of rearing temperature and experimental heating rate. <strong><em>Journal of Thermal Biology</em> </strong>90,102582. <a href="https://doi.org/10.1016/j.jtherbio.2020.102582" target="_blank">https://doi.org/10.1016/j.jtherbio.2020.102582</a><br />IF: 2.902, Citations: n/a, Altmetric: 13</p>
            <p>69) Staaterman, E., Gallagher, A.J., Holder, P.E., Reid, C.H., Altieri, A.H., Ogburn, M.B., Rummer, J.L., Cooke, S.J. (2020) Exposure to boat noise in the field yields minimal stress response in wild reef fish. <em>Aquatic Biology</em> 29, 93-103. doi: <a href="https://doi.org/10.3354/ab00728">https://doi.org/10.3354/ab00728</a>IF: 1.588, Citations: 1, Altmetric: 8</p>
            <p>68) <u>Laubenstein, T.D.</u>, Jarrold, M.D., <strong>Rummer, J.L.</strong>, Munday, P.L. (2020) Beneficial effects of diel CO2 cycles on reef fish metabolic performance are diminished under elevated temperature. <strong><em>Science of the Total Environment</em></strong> 735, 139084. doi: <a href="https://doi.org/10.1016/j.scitotenv.2020.139084" target="_blank">https://doi.org/10.1016/j.scitotenv.2020.139084</a> <br />IF: 7.963, Citations: 2, Altmetric: 6</p>
            <p>67) Cooke, S.J., Madliger, C.L., Cramp, R.L., Beardall, J., Burness, G.P., Chown, S.L., Clark, T.D., Dantzer, B., de la Barrera, E., Fangue, N.A., Franklin, C.E., Fuller, A., Hawkes, L.A., Hultine, K.R., Hunt, K.E., Love, O.P., MacMillan, H.A., Mandelman, J.W., Mark, F.C., Martin, L.B., Newman, A.E.M., Nicotra, A.B., Robinson, S.A., Ropert-Coudert, Y., <strong>Rummer, J.L.</strong>, Seebacher, F., Todgham, A.E. (2020) Reframing conservation physiology to be more inclusive, integrative, relevant and forward-looking: reflections and a horizon scan. <strong><em>Conservation Physiology</em></strong> 8,coaa016. doi: <a href="https://dx.doi.org/10.1093/conphys/coaa016" target="_blank">10.1093/conphys/coaa016</a><br />IF: 3.079, Citations: n/a, Altmetric: 33</p>
            <p>66) <u>Downie, A.T.</u>, <u>Illing, B.</u>, Faria, A.M., and <strong>Rummer, J.L. </strong>(2020) Swimming performance of marine fish larvae: review of a universal trait under ecological and environmental pressure. <strong><em>Reviews in Fish Biology and Fisheries </em></strong>30,93-108. <a href="https://doi.org/10.1007/s11160-019-09592-w">https://doi.org/10.1007/s11160-019-09592-w</a><br />IF: 4.43, Citations: 18, Altmetric: 46</p>
            <p>65) Bernal, M.A., Schunter, C., Lehmann, R., Lightfoot, D.J., Allan, B.J.M., Veilleux, H.D., <strong>Rummer, J.L.</strong>, Munday, P.L., &amp; Ravasi, T. (2020) Molecular responses of a coral reef fish to a marine heatwave. <strong><em>Science Advances</em></strong> 6(12), eaay3423. <a href="https://doi.org/10.1126/sciadv.aay3423">https://doi.org/10.1126/sciadv.aay3423</a><br />IF: 14.136, Citations: n/a, Altmetric: n/a<br />*this research was highlighted in the media and via press releases</p>
            <p>64) Schwieterman, G.D., Bouyoucos, I.A., Potgieter, K., Simpfendorfer, C.A., Brill, R.W., <strong>Rummer, J.L.</strong> (2019) Analyzing tropical elasmobranch blood samples in the field: Blood stability during storage and validation of the HemoCue&reg; haemoglobin analyser. <strong><em>Conservation Physiology </em></strong>7(1),coz081. doi: <a href="https://doi.org/10.1093/conphys/coz081">https://doi.org/10.1093/conphys/coz081</a>.<br />IF: 3.079, Citations: 9, Altmetric: 10</p>
            <p>63) <u>Weideli, O.C.</u>, <u>Bouyoucos, I.A.</u>, Papastamatiou, Y.P., Mescam, G., <strong>Rummer, J.L.</strong>, Planes, S. (2019) Same species, different prerequisites: investigating body condition and foraging success in young reef sharks between an atoll and an island system. <strong><em>Scientific Reports </em></strong>9,13447. doi: <a href="https://doi.org/10.1038/s41598-019-49761-2">https://doi.org/10.1038/s41598-019-49761-2</a><br />IF: 4.379, Citations: n/a, Altmetric: 46</p>
            <p>62) <u>Bouyoucos, I.A.</u>, Simpfendorfer, C.A., <strong>Rummer, J.L.</strong> (2019) Estimating oxygen uptake rates to understand stress in sharks and rays. <strong><em>Reviews in Fish Biology &amp; Fisheries </em></strong>29(2):297-311. doi: <a href="https://doi.org/10.1007/s11160-019-09553-3">https://doi.org/10.1007/s11160-019-09553-3</a><br />IF: 4.43, Citations: 1, Altmetric: 29</p>
            <p>61) <u>Spady, B.L.</u>, <u>Nay, T.J.</u>, <strong>Rummer, J.L.</strong>, Munday, P.L., Watson, S-A. (2019). Aerobic performance of two tropical cephalopod species unaltered upon prolonged exposure to projected future carbon dioxide levels. <strong><em>Conservation Physiology </em></strong>7(1):coz024. <a href="https://doi.org/10.1093/conphys/coz024">https://doi.org/10.1093/conphys/coz024</a> <br />IF: 3.079, Citations: n/a, Altmetric: 110<br />*this research was highlighted in the media and via press releases</p>
            <p>60) <u>Laubenstein, T.D.</u>, <strong>Rummer, J.L.</strong>, McCormick, M.I., Munday, P.L. (2019). A negative correlation between behavioural and physiological performance under ocean acidification and warming. <strong><em>Scientific Reports </em></strong>9:4265. Doi: <a href="https://doi.org/10.1038/s41598-018-36747-9">https://doi.org/10.1038/s41598-018-36747-9</a><br />IF: 4.379, Citations: n/a, Altmetric: 27<br />*this research was highlighted in the media and via press releases, this paper was also one of the top 100&nbsp;downloaded ecology&nbsp;papers for&nbsp;<em>Scientific Reports</em>&nbsp;in 2019</p>
            <p>59) <u>Rodgers, G.G.</u>, <strong>Rummer, J.L.</strong>, Johnson, L.K., McCormick, M.I. (2018). Impacts of increased ocean temperatures on a low-latitude coral reef fish &ndash; processes related to oxygen uptake and delivery. <strong><em>Journal of Thermal Biology </em></strong>79: 95-102. <a href="https://doi.org/10.1016/j.jtherbio.2018.12.008">https://doi.org/10.1016/j.jtherbio.2018.12.008</a><br />IF: 2.902, Citations: n/a, Altmetric: n/a</p>
            <p>58) <u>Gervais, C.R.,</u> <u>Nay, T.J.</u>, Renshaw, G., Johansen, J.L., Steffensen, J.F., <strong>Rummer, J.L. </strong>(2018) Too hot to handle? Using movement to alleviate the effects of elevated temperatures in a benthic elasmobranch, <em>Hemiscyllium ocellatum</em>. <strong><em>Marine Biology </em></strong>165:162. <a href="https://doi.org/10.1007/s00227-018-3427-7">https://doi.org/10.1007/s00227-018-3427-7</a><br />IF: 2.941, Citations: 17, Altmetric: 59</p>
            <p>57) <u>Hess, S.</u>, Allan, B.J.M., Hoey, A.S., Jarrold, M.D., Wenger, A.S., <strong>Rummer, J.L. </strong>(2018) Enhanced fast start performance and anti-predator behaviour in a coral reef fish in response to suspended sediment exposure. <strong><em>Coral Reefs </em></strong>38(1): 103-108. <a href="https://doi.org/10.1007/s00338-018-01757-6">https://doi.org/10.1007/s00338-018-01757-6</a><br />IF: 3.902, Citations: n/a, Altmetric: 78<br />*this research was highlighted in the media and via press releases</p>
            <p>56) <u>Bouyoucos, I.A.,</u> <u>Weideli, O.C.</u>, Planes, S., Simpfendorfer, C.A., <strong>Rummer, J.L. </strong>(2018) Dead tired: Evaluating the physiological status and survival of neonatal reef sharks under stress. <strong><em>Conservation</em></strong><em> <strong>Physiology</strong> </em>6:1 coy053. <a href="https://doi.org/10.1093/conphys/coy053">https://doi.org/10.1093/conphys/coy053</a><br />IF: 3.079, Citations: n/a, Altmetric: 38</p>
            <p>55) Berthe, C., Waqalevu, V.P., Latry, L., Besson, M., Lerouvreur, F., Siu, G., Lecellier, G., <strong>Rummer J.L.</strong>, Bertucci, F., Igl&eacute;sias, S.,&nbsp;Lecchini, D.&nbsp;(2018).&nbsp;Distribution patterns of ocellated eagle rays,&nbsp;<em>Aetobatus </em><em>ocellatus,&nbsp;</em>along two sites in Moorea Island, French Polynesia. <strong><em>Cybium</em></strong> 42(4)313-320. <a href="https://doi.org/10.26028/cybium/2018-424-002">https://doi.org/10.26028/cybium/2018-424-002</a><br />IF: 0.560, Citations: 0, Altmetric: n/a</p>
            <p>54) <u>Nay, T.J.,</u> <u>Gervais, C.R.</u>, Hoey, A.S., Johansen, J.F., Steffensen, J.F., <strong>Rummer, J.L.</strong> (2018) The emergence emergency: a mudskipper&rsquo;s response to temperatures. <strong><em>Journal of Thermal Biology</em></strong> 78:65-72 doi: <a href="https://doi.org/10.1016/j.jtherbio.2018.09.005" target="_blank">https://doi.org/10.1016/j.jtherbio.2018.09.005</a><br />IF: 2.902, Citations: n/a, Altmetric: 15</p>
            <p>53) <u>Laubenstein, T.D.</u>, <strong>Rummer, J.L.</strong>, Nicol, S., Parsons, D.M., Pether, S.M.J., Pope, S., Smith, N., Munday, P.L. (2018) Correlated effects of ocean acidification and warming on behavioural and metabolic traits of a large pelagic fish. <strong><em>Diversity</em></strong> <em>10</em>(2): 35. <a href="https://doi.org/10.3390/d10020035">https://doi.org/10.3390/d10020035</a><br />IF: 2.465, Citations: n/a, Altmetric: 29</p>
            <p>52) <u>Jain-Schlaepfer, S.</u>, Faken, E., <strong>Rummer, J.L.</strong>, Simpson, S.D., McCormick, M.I. (2018) Impact of motorboats on fish embryos depends on engine type. <strong><em>Conservation Physiology </em></strong>6:coy014. <a href="https://doi.org/10.1093/conphys/coy014">https://doi.org/10.1093/conphys/coy014</a><br />IF: 3.079, Citations: n/a, Altmetric: 53<br />*this research was highlighted in the media and via press releases</p>
            <p>51) Lopes, A.R., Sampaio, E., Santos, C., Couto, A., Pegado, M.R. Diniz, M., Munday, P.L., <strong>Rummer, J.L.</strong>, Rosa, R. (2018) Absence of cellular damage in tropical newly-hatched sharks (<em>Chiloscyllium plagiosum</em>) under ocean acidification conditions. <strong><em>Cell Stress &amp; Chaperones</em></strong> 23(5):837-846. doi: 0.1007/s12192-018-0892-3 <br />IF: 3.667, Citations: n/a, Altmetric: 6</p>
            <p>50) <u>Hannan, K.D.</u>, <strong>Rummer, J.L. </strong>(2018) Aquatic acidification: A mechanism underpinning maintained oxygen transport and performance in fish experiencing elevated carbon dioxide conditions. <strong><em>Journal of Experimental Biology </em></strong>221(5):&nbsp;jeb154559&nbsp;doi:&nbsp;10.1242/jeb.154559.<br />IF: 3.312, Citations: 0, Altmetric: 33</p>
            <p>49) <u>Hess, S.,</u> <u>Prescott, L.J.</u>, Hoey, A.S., McMahon, S.A., Wenger, A.S., <strong>Rummer, J.L. </strong>(2017) Species-specific impacts of suspended sediments on gill structure and function in coral reef fishes. <strong><em>Proceedings of the Royal Society &ndash; B </em></strong>284(1866) 20171279. doi: 10.1098/rspb.2017.1279<br />IF: 5.349, Citations: 1, Altmetric: 78<br />*this research was highlighted in the media and via press releases</p>
            <p>48) Schunter, C., Welch, M.J., Nilsson, G.E., <strong>Rummer, J.L.</strong>, Munday, P.L., Ravasi, T. (2017) An interplay between plasticity, epigenetics, and parental phenotype determines impacts of ocean acidification on a reef fish. <strong><em>Nature Ecology &amp; Evolution </em></strong>doi: 10.1038/s41559-017-0428-8.<br />IF: 12.543, Citations: 3, Altmetric: 39</p>
            <p>47) Cooke, S.J., Birnie-Gauvin, K., Lennox, R.J., Taylor, J.J., Rytwinski, T., <strong>Rummer, J.L.</strong>, Franklin, C.E., Bennett, J.R., Haddaway, N.R. (2017) How experimental biology and ecology can support evidence-based decision making in conservation: Avoiding pitfalls and enabling application. <strong><em>Conservation Physiology </em></strong>5&nbsp;(1):cox043. doi:&nbsp;10.1093/conphys/cox043<br />IF: 3.079, Citations: 3, Altmetric: 22</p>
            <p>46) Ern, R., Johansen, J.L., <strong>Rummer, J.L.</strong>, Esbaugh, A.J. (2017) Effects of hypoxia and ocean acidification on the upper thermal niche boundaries of coral reef fishes. <strong><em>Biology Letters </em></strong>13(7):20170135. doi: 10.1098/rsbl.2017.0135<br />IF: 3.703, Citations: 3, Altmetric: 16</p>
            <p>45) Johansen, J.L., Allan, B.J.M., <strong>Rummer, J.L.</strong>, Esbaugh, A.J. (2017) Oil exposure disrupts early life-history stages of coral reef fishes via behavioural impairments. <strong><em>Nature Ecology &amp; Evolution </em></strong>1(8)1146. doi: 10.1038/s41559-017-0232-5<br />IF: 12.543, Citations: 1, Altmetric: 226<br />*this research was highlighted in the media and via press releases</p>
            <p>44) Rosa, R., <strong>Rummer, J.L.</strong>, Munday, P.L. (2017) Biological Responses of sharks to ocean acidification. <strong><em>Biology Letters</em></strong> 13(3) 20160796. <a href="https://doi.org/10.1098/rsbl.2016.0796">https://doi.org/10.1098/rsbl.2016.0796</a><br />IF: 3.812, Citations: 49, Altmetric: 60</p>
            <p>43) Talwar, B., Bouyoucos, I.A., Shipley, O., <strong>Rummer, J.L.</strong>, Mandelman, J.W., Brooks, E.J., Grubbs, R.D. (2017) Validation of a portable, waterproof blood pH analyzer for elasmobranchs. <strong><em>Conservation Physiology </em></strong>5 (1): cox012. doi:<a href="https://doi-org.elibrary.jcu.edu.au/10.1093/conphys/cox012">10.1093/conphys/cox012</a><br />IF: 3.079, Citations: 1, Altmetric: 9</p>
            <p>42) Illing, B., <strong>Rummer, J.L. </strong>(2017) Physiology can contribute to better understanding, managing, and conserving coral reef fishes. <strong><em>Conservation Physiology </em></strong>5&nbsp;(1):cox005. doi:&nbsp;10.1093/conphys/cox005<br />IF: 3.079, Citations: 1, Altmetric: 20</p>
            <p>41) Madliger, C.L., Franklin, C.E., Hultine, K.R., van Kleunen, M., Lennox, R.J., Love, O.P., <strong>Rummer, J.L.</strong>, Cooke, S.J. (2017) Conservation physiology and the quest for a &ldquo;good&rdquo; Anthropocene. <strong><em>Conservation Physiology </em></strong>5&nbsp;(1):cox003. doi:&nbsp;10.1093/conphys/cox003<br />IF: 3.079, Citations: 2, Altmetric: 25</p>
            <p>40) Heuer, R.M., Welch, M.J., <strong>Rummer, J.L.</strong>, Munday, P.L., Grosell, M. (2016) Altered brain ion gradients following compensation for elevated CO2 are linked to behavourial alterations in a coral reef fish. <strong><em>Scientific Reports</em></strong> 6, 33216; doi: 10.1038/srep33216.<br />IF: 4.379, Citations: 14, Altmetric: 80<br />*this research was highlighted in the media and via press releases</p>
            <p>39) <u>Habary, A.</u>, Johansen, J.L., <u>Nay, T.J.</u>, Steffensen, J.F.,<strong> Rummer, J.L.</strong> (2017) Adapt, move, or die &ndash; how will coral reef fishes cope with ocean warming? <strong><em>Global Change Biology</em></strong> 23(2):566-577. doi:&nbsp;10.1111/gcb.13488<br />&nbsp;IF: 10.863, Citations: 5, Altmetric: 122<br />*this research was highlighted in the media and via press releases</p>
            <p>38)<strong> Rummer, J.L.</strong>, Munday, P.L. (2017) Climate change and the evolution of reef fishes: past and future. <strong><em>Fish and Fisheries</em></strong> 18(1): 22-39. doi: 10.1111/faf.12164<br />IF: 6.785, Citations: 6, Altmetric: 41</p>
            <p>37) <u>Johnson, M.S.</u>, <u>Kraver, D.W.</u>, Renshaw, G.M.C.,<strong> Rummer, J.L.</strong> (2016) Will ocean acidification affect the early ontogeny of a tropical oviparous elasmobranch (<em>Hemiscyllium ocellatum</em>)? <strong><em>Conservation Physiology</em></strong> 4&nbsp;(1):cow003. <a href="https://doi.org/10.1093/conphys/cow003">https://doi.org/10.1093/conphys/cow003</a><br />IF: 3.079, Citations: 18, Altmetric: 167<br />*this research was highlighted in the media and via press releases</p>
            <p>36) <u>Gervais, C.</u>, Mourier, J., <strong>Rummer, J.L.</strong> (2016) Developing in warm water: Irregular colouration and patterns of a neonate elasmobranch. <strong><em>Marine Biodiversity </em></strong>2016:1-2. <a href="https://doi.org/10.1007/s12526-015-0429-2">https://doi.org/10.1007/s12526-015-0429-2</a><br />IF: 1.815, Citations: 10, Altmetric: 42</p>
            <p>35)<strong> Rummer, J.L.</strong>, Binning, S.A., Roche, D.G., Johansen, J.L. (2016) Methods matter: Considering locomotory mode and respirometry technique for estimating metabolic rate in fish. <strong><em>Conservation Physiology</em></strong> 4&nbsp;(1):&nbsp;cow008&nbsp;doi:10.1093/conphys/cow008.<br />IF: 3.079, Citations: 5, Altmetric: 10</p>
            <p>34) Chin, A., Mourier, J., <strong>Rummer, J.L. </strong>(2015) Blacktip reef sharks (<em>Carcharhinus melanopterus</em>) show high capacity for wound healing and recovery following injury. <strong><em>Conservation Physiology </em></strong>3&nbsp;(1):cov062. doi:10.1093/conphys/cov062<br />IF: 3.079, Citations: 10, Altmetric: 96</p>
            <p>33)&nbsp;Berthe, C., Mourier, J., Lecchini, D., <strong>Rummer, J.L.</strong>, Sellos, D.Y., Igl&eacute;sias, S.P. (2016) DNA barcoding supports the presence of the crypic Ocellated Eagle Ray, <em>Aetobatus ocellatus</em> (Myliobatidate), in French Polynesia, South Pacific. <strong><em>Cybium </em></strong>40(2):182-184. <br />IF: 0.560, Citations: 0, Altmetric: 0</p>
            <p>32) <strong>Rummer, J.L.</strong>, Brauner, C.J. (2015) Root effect haemoglobins in fish may greatly enhance general oxygen delivery relative to other vertebrates. <strong><em>PLoS One</em></strong> 10(10):e0139477. doi:10.1371/journal.pone.0139477<br />IF: 3.240, Citations: 9, Altmetric: 189<br />*this research was highlighted in the media and via press releases</p>
            <p>31) <u>Nay, T.J.</u>, Johansen, J.L., <u>Habary, A.</u>, Steffensen, J.F., <strong>Rummer, J.L.</strong> (2015) Behavioural thermoregulation in a temperature-sensitive coral reef fish species, the five-lined cardinalfish (<em>Cheilodipterus quinquelineatus</em>). <strong><em>Coral Reefs</em></strong> 34(4):1261-1265. doi: 10.1007/s00338-015-1353-4<br />IF: 3.902, Citations: 5, Altmetric: 9</p>
            <p>30) Cinner, J., Pratchett, M.S., Graham, N.A.J., Messmer, V., Fuentes, M.M.P.B., Ainsworth, T., Ban, N.C., Bay, L.K., Blythe, J.L., Dissard, D., Dunn, S., Evans, L.S., Fabinyi, M., Fidelman, P., Figueiredo, J., Frisch, A.J., Fulton, C.J., Hicks, C.C., Lukoschek, V., Mallela, J., Moya, A., Penin, L., <strong>Rummer, J.L.</strong>, Walker, S., Williamson, D.H. (2015) A Framework for understanding climate change impacts on coral reef social-ecological systems. <strong><em>Regional Environmental Change</em></strong> 1-15. doi: 10.1007/s10113-015-0832-z<br />IF: 3.678, Citations: 18, Altmetric: 62</p>
            <p>29) <u>Hess, S.</u>, <u>Wenger, A.S.</u>, Ainsworth, T., <strong>Rummer, J.L. </strong>(2015) Exposure of clownfish larvae to suspended sediment levels found on the Great Barrier Reef: Impacts on gill structure and microbiome. <strong><em>Scientific Reports</em></strong> 5. doi:10.1038/srep10561<br />IF: 4.379, Citations: 26, Altmetric: 49<br />*this research was highlighted in the media and via press releases</p>
            <p>28) <u>Heinrich, D.D.U.</u>, Watson, S-A., <strong>Rummer, J.L.</strong>, Brandl, S.J., Simpfendorfer, C.A., Heupel, M.R., Munday, P.L. (2015) Foraging behaviour of the epaulette shark <em>Hemiscyllium ocellatum</em> is not affected by ocean acidification. <strong><em>ICES Journal of Marine Science</em></strong> 73(3), 633-640. <a href="https://doi.org/10.1093/icesjms/fsv085">https://doi.org/10.1093/icesjms/fsv085</a>.<br />IF: 3.906, Citations: 39, Altmetric: 118</p>
            <p>27) Baker, D.W., Sardella, B., <strong>Rummer, J.L</strong>., Sackville, M., Brauner, C.J. (2015) Hagfish: Champions of CO2 tolerance question the origins of vertebrate gill function<em>.</em> <strong><em>Scientific Reports</em></strong> 5:11182. doi:10.1038/srep11182<br />IF: 4.379, Citations: 10, Altmetric: 56<br />*this research was highlighted in the media and via press releases</p>
            <p>26) Harter, T.S., Morrison, P.R., Mandelman, J.W., <strong>Rummer, J.L.</strong>, Farrell, A.P., Brill, R.W., Brauner, C.J. (2015) Validation of the i-STAT system for the analysis of blood gases and acid-base status in juvenile sandbar shark <strong><em>Conservation Physiology</em></strong> 3(1):cov002. doi:&nbsp;10.1093/conphys/cov002.<br />IF: 3.079, Citations: 8, Altmetric: 3</p>
            <p>25) Ferrari, M.C.O., Munday, P.L., <strong>Rummer, J.L.</strong>, McCormick, M.I., Corkill, K., Watson, S-A., Allan, B.J.M, Meekan, M.G., Chivers, D.P. (2015) Interactive effects of ocean acidification and rising sea temperatures alter prey mortality and predator selectivity in reef fish communities. <strong><em>Global Change Biology</em></strong> 21(5), 1848-1855. doi:&nbsp;10.1111/gcb.12818.<br />IF: 10.863, Citations: 31, Altmetric: 25</p>
            <p>24) Heinrich, D.D.U., Rummer, J.L., Morash, A.J., Watson, S-A., Simpfendorfer, C.A, Heupel, M.R., Munday, P.L. (2014) A product of its environment: The epaulette shark (<em>Hemiscyllium ocellatum</em>) exhibits physiological tolerance to elevated environmental CO2. <strong><em>Conservation Physiology</em></strong> 2, cou047. <a href="https://doi.org/10.1093/conphys/cou047">https://doi.org/10.1093/conphys/cou047</a>.<br />IF: 3.079, Citations: 45, Altmetric: 160<br />*this research was highlighted in the media and via press releases</p>
            <p>23) <u>Bowden, A.J.</u>, Gardiner, N.M., Couturier, C.S., Stecyk, J.A.W., Nilsson, G.E., Munday, P.L., <strong>Rummer, J.L.</strong> (2014) Alterations in gill structure in tropical reef fishes as a result of elevated temperatures. <strong><em>Comparative Biochemistry &amp; Physiology A</em></strong> 175:64-71. doi:10.1016/j.cbpa.2014.05.011.<br />IF: 2.320, Citations: 12, Altmetric: 4</p>
            <p>22) Killen, S.S, Mitchell, M.D., <strong>Rummer, J.L.</strong>, Chivers, D.P., Ferrari, M.C.O., Meekan, M., McCormick, M.I. (2014) Aerobic scope predicts dominance during early life in a tropical damselfish. <strong><em>Functional Ecology</em></strong> 28(6), 1367-1376. doi:10.1111/1365-2435.12296.<br />IF: 5.610, Citations: 45, Altmetric: 3</p>
            <p>21) Munday, P.L., Cheal, A., Dixson, D.L.,<strong> Rummer, J.L. </strong>Fabricius, K. (2014) Behavioural impairment in reef fishes caused by ocean acidification at CO2 seeps. <strong><em>Nature Climate Change</em></strong> 4, 487-492. doi:10.1038/NCLIMATE2195<br />IF: 25.290, Citations: 94, Altmetric: 225<br />*this research was highlighted in the media and via press releases</p>
            <p>20) Randall, D.J., <strong>Rummer, J.L.</strong>, Wilson, J.M. Wang, S., Brauner, C.J. (2014) Review: A unique mode of tissue oxygenation and the success of teleost fish. <strong><em>Journal of Experimental Biology</em></strong> 217, 1205-1214. doi:10.1242/jeb.093526.<br />IF: 3.312, Citations: 19, Altmetric: 1</p>
            <p>19) <strong>Rummer, J.L.</strong>, Couturier, C.S., Stecyk, J.A.W., Gardiner, N.M., Kinch, J.P., Nilsson, G.E., Munday, P.L. (2014) Life on the edge: Thermal optima for aerobic scope of equatorial reef fishes are close to current day temperatures. <strong><em>Global Change Biology</em></strong> 20(4):1055-66. doi:10.1111/gcb.12455<br />IF: 10.863, Citations: 137, Altmetric: 71<br />*this research was highlighted in the media and via press releases</p>
            <p>18) <strong>Rummer, J.L.</strong>, Wang, S., Steffensen, J.F., Randall, D.J. (2014) Function and control of the fish secondary vascular system, a contrast to mammalian lymphatic systems<em>. <strong>Journal of Experimental Biology</strong> </em>217(5):751-757. doi:10.1242/jeb.086348.<br />IF: 3.312, Citations: 10, Altmetric: 14</p>
            <p>17) <strong>Rummer, J.L.</strong>, McKenzie, D.J., Innocenti, A., Supuran, C.T., Brauner, C.J. (2013) Root effect haemoglobin may have evolved to enhance general oxygen delivery. <strong><em>Science</em></strong> 340, 1327-1329. doi:10.1126/science.1233692<br />IF: 47.728, Citations: 87, Altmetric: 197<br />*this research was highlighted in the media and via press releases</p>
            <p>16) <u>Collins, G.</u>, Clark, T.D., <strong>Rummer, J.L.</strong>, Carton, A.G. (2013) Hypoxia tolerance is conserved across genetically distinct sub-populations of an iconic, tropical Australian teleost (<em>Lates calcarifer</em>) <strong><em>Conservation Physiology</em></strong> 1, cot029. doi:10.1093/conphys/cot029.<br />IF: 3.079, Citations: 15, Altmetric: 1</p>
            <p>15) <strong>Rummer, J.L.</strong>, Stecyk, J.A.W., Couturier, C.S., Watson, S-A., Nilsson, G.E., Munday, P.L. (2013) Elevated CO2 enhances aerobic scope of a coral reef fish. <strong><em>Conservation Physiology</em></strong> 1, cot023. doi:10.1093/conphys/cot023.<br />IF: 3.079, Citations: 41, Altmetric: 3</p>
            <p>14) <u>McLeod, I.M.</u>, <strong>Rummer, J.L.</strong>, Clark, T.D., Jones, G.P., Wenger, A.S., McCormick, M.I., Munday, P.L. (2013) Climate change and the performance of larval coral reef fishes: the interaction between temperature and food availability. <strong><em>Conservation Physiology</em></strong> 1, cot024. doi:10.1093/conphys/cot024.<br />IF: 3.079, Citations: 30, Altmetric: 1</p>
            <p>13) Couturier, C.S., Stecyk, J.A.W., <strong>Rummer, J.L.</strong>, Munday, P.L., Nilsson, G.E. (2013) Species-specific effects of near-future CO2 on the respiratory performance of two tropical prey fish and their predator. <strong><em>Comparative Physiology &amp; Biochemistry A</em></strong> 166:482&ndash;489. doi:10.1016/j.cbpa.2013.07.025.<br />IF: 2.320, Citations: 45, Altmetric: 6</p>
            <p>12) Roche, D.G., Binning, S.A., Bosiger, Y., Johansen, J.L., <strong>Rummer, J.L. </strong>(2013) Finding the best estimates for metabolic rates in a coral reef fish. <strong><em>Journal of Experimental Biology</em></strong> 216, 2103-2110. doi:10.1242/jeb.082925.<br />IF: 3.312, Citations: 65, Altmetric: 1</p>
            <p>11) Dabruzzi, T.F., Fangue, N.A., <strong>Rummer, J.L.</strong>, Bennett, W.A. (2013) Juvenile ribbontail stingray, <em>Taeniura lymma</em> (Forssk&aring;l, 1775) demonstrate a unique suite of physiological adaptations to survive hyperthermic nursery conditions. <strong><em>Hydrobiologia</em></strong> 701, 37-49. doi:10.1007/s10750-012-1249-z.<br />IF: 2.694, Citations: 4, Altmetric: 6</p>
            <p>10) <strong>Rummer, J.L.</strong>, Brauner, C.J. (2011) Plasma-accessible carbonic anhydrase at the tissue of a teleost fish may greatly enhance oxygen delivery: <em>in vitro</em> evidence in rainbow trout, <em>Oncorhynchus mykiss</em><em>. <strong>Journal of Experimental Biology</strong></em> 214, 2319-2328. doi:10.1242/jeb.054049<br />IF: 3.312, Citations: 29, Altmetric: n/a</p>
            <p>9) Wang, J., <strong>Rummer, J.L.</strong>, Niu, C.J., Xie, Z., Huang, C. Qian, Y., Liu, Y. (2011) Compensatory growth in juvenile Chinese three-keeled pond turtles, <em>Chinemys reevesii</em>. <strong><em>Journal of the World Aquaculture Society</em></strong> 42(1): 82-89. doi:10.1111/j.1749-7345.2010.00446.x.<br />IF: 2.512, Citations: 5, Altmetric: n/a</p>
            <p>8) <strong>Rummer, J.L.</strong>, <u>Roshan-Moniri, M.</u>, Balfry, S.K., Brauner, C.J. (2010) Use it or lose it? Sablefish, <em>Anoplopoma</em> <em>fimbria</em>, a species representing a fifth teleostean group where the bNHE associated with the red blood cell adrenergic stress response has been secondarily lost. <strong><em>Journal of Experimental Biology</em></strong> 213, 1503-1512. doi:10.1242/jeb.038844.<br />IF: 3.312, Citations: 12, Altmetric: n/a</p>
            <p>7) Clark, T.D., <strong>Rummer, J.L.</strong>, Sepulveda, C.A., Farrell, A.P., Brauner, C.J. (2009) Reduced and reversed temperature dependence of blood oxygenation in an ectothermic scombrid fish: implications for the evolution of regional heterothermy? <strong><em>Journal of Comparative Physiology B: Biochemical, Systems, and Environmental Physiology</em> </strong>180(1):73-82. doi:10.1007/s00360-009-0388-7.<br />IF: 2.200, Citations: 11, Altmetric: n/a</p>
            <p>6)<strong> Rummer, J. L.</strong>, Fangue, N. A. Jordan, H. L. Tiffany, B. N. Blansit, K. J. Galleher, S. Kirkpatrick, A. Kizlauskus, A. Pomory, C. M., Bennett, W. A. (2009) Physiological tolerance to hyperthermia and hypoxia and effects on species richness and distribution of rockpool fishes of Loggerhead Key, Dry Tortugas National Park. <strong><em>Journal of Experimental Marine Biology &amp; Ecology</em></strong> 371(2):155-162. doi:10.1016/j.jembe.2009.01.015.<br />IF: 2.171, Citations: 14, Altmetric: n/a</p>
            <p>5) Niu, C.J., <strong>Rummer, J.L.</strong> Brauner, C. J., Schulte, P.M. (2008) Heat shock protein (Hsp 70) induced by mild heat shock inhibits sharp plasma osmolarity increase upon seawater transfer in rainbow trout (<em>Oncorhynchus mykiss</em>). <strong><em>Comparative Biochemistry &amp; Physiology C</em></strong> 138:437-444. doi:10.1016/j.cbpc.2008.04.011.<br />IF: 3.228, Citations: 33, Altmetric: n/a</p>
            <p>4) Lai, J.C.C., Kakuta, I. Mok, H.O.L. <strong>Rummer</strong>, <strong>J. L., </strong>Randall, D. J. (2006) Effects of moderate and severe hypoxia on erythropoietin levels in rainbow trout kidney and spleen. <strong><em>Journal of Experimental Biology</em> </strong>209: 2734-2738. doi:10.1242/jeb.02279.<br />IF: 3.312, Citations: 89, Altmetric: n/a</p>
            <p>3) Caldwell, S., <strong>Rummer</strong>, <strong>J.L., </strong>Brauner, C.J. (2006) Blood sampling techniques and storage duration: Effects on the presence and magnitude of the red blood cell b-adrenergic response in rainbow trout, <em>Oncorhynchus mykiss</em>. <strong><em>Comparative Biochemistry and Physiology</em> <em>A</em></strong> 144(2): 188-195. doi:10.1016/j.cbpa.2006.02.029.<br />IF: 2.320, Citations: 21, Altmetric: n/a</p>
            <p>2)<strong> Rummer, J. L.</strong>, Bennett, W.A. (2005) Physiological effects of swim bladder overexpansion and catastrophic decompression on red snapper, <em>Lutjanus campechanus</em>. <strong><em>Transactions of the American Fisheries Society</em></strong> 134(6): 1457-1470. doi:10.1577/T04-235.1<br />IF: 1.861, Citations: 114, Altmetric: n/a<br />*this research was highlighted in the media and via press releases</p>
            <p>1) Fangue, N. A., Flaherty, K. E. <strong>Rummer</strong>, <strong>J. L. </strong>Cole, G. Hansen, K. S. Hinote, R. Noel, B. L. Wallman, H., Bennett, W.A. (2001) Temperature and hypoxia tolerance of selected fishes from a hyperthermal rockpool in the Dry Tortugas, with notes on diversity and behavior. <strong><em>Caribbean Journal of Science</em></strong> 37(1-2): 81-87. doi:10.1086/589109.IF: 0.200, Citations: 20, Altmetric: n/a<br />&nbsp;<br /><strong><u>Conference Proceedings</u></strong><strong>:</strong><br />8) Hernandez, A., <u>Gervais, C.R.</u>, <strong>Rummer, J.L.</strong>, Porter, M.E. (2016) Comparing submerged walking and swimming kinematics in epaulette sharks. <em>Integrative and Comparative Biology</em> 56: E301.</p>
            <p>7) <u>Hess, S.</u>, Wenger, A., Ainsworth, A., <strong>Rummer, J.L. </strong>(2015) Too turbid for nemo: Suspended sediment impacts gills and favours pathogenic bacteria in clownfish larvae. 145th Annual Meeting of the American Fisheries Society.</p>
            <p>6) <strong>Rummer, J.L.</strong>, Morash, A.J., Miller, G., Iftikar, F.I., Hickey, A., Wilson, J., Munday, P.L. (2015) Effects of ocean acidification on metabolic performance in coral reef fishes. 145th Annual Meeting of the American Fisheries Society.</p>
            <p>5)<strong> Rummer, J. L.</strong>, Brauner, C.J. (2008) Beyond buoyancy and vision: The potential for the Root effect to facilitate oxygen delivery to tissues other than the swimbaldder and eye. <strong><em>Comparative Biochemistry and Physiology Part A: Molecular and Integrative Physiology</em></strong> 150(3): S52-S53.</p>
            <p>4) Baker, D.,<strong> Rummer, J. L.</strong>, Sardella, B., Brauner, C.J. (2006) Acid-base regulation during exposure to elevated environmental CO2 in an osmoconformer, the Pacific hagfish (<em>Eptatretus stoutii</em>). <strong><em>Comparative Biochemistry and Physiology Part A: Molecular and Integrative Physiology</em></strong> 143(4): S74-S74.</p>
            <p>3) <strong>Rummer, J. L.</strong>, Machala, A.M., Grant, A., Balfry, S.K., Higgs, D.A., Devlin, R., Schulte, P.M., Brauner, C.J. (2006) A swimmer&rsquo;s diet: Substituting dietary lipids and the resulting effects on swimming performance in Chinook salmon (<em>Oncorhynchus tshawytscha</em>). <strong><em>Comparative Biochemistry and Physiology Part A: Molecular and Integrative Physiology </em></strong>143(4): S72-S72.</p>
            <p>2) <strong>Rummer, J. L.</strong>, Regan, M., Brauner, C.J. (2006) Characterization of the haemoglobin and red blood cell system in the copper rockfish, <em>Sebastes caurinus</em>. <strong><em>Comparative Biochemistry and Physiology Part A: Molecular and Integrative Physiology</em></strong> 143(4): S74-S74.</p>
            <p>1) Regan, M., Kuchel, L.,<strong> Rummer, J. L.</strong>, Machala, A., Grant, A., Schulte, P., Brauner, C.J., Balfry, S., Higgs, D., Devlin, R.H. (2006) Effects of dietary lipid substitution on swimming performance during the early developmental stages of Chinook salmon (<em>Oncorhynchus tshawytscha</em>). <strong><em>Comparative Biochemistry and Physiology Part A: Molecular and Integrative Physiology</em></strong> 143(4): S72-S72. doi:10.1016/j.cbpa.2006.01.039.<br />&nbsp;<br /><strong><u>Editorial Commentaries and Perspectives</u></strong><strong>:</strong><br />21) <strong>Rummer, J.L.</strong>, Heron, S.H. (2022) What the next Australian government must do to save the Great Barrier Reef.<strong><em> The Conversation</em></strong>. 12 May 2022. <a href="https://bit.ly/3NfTRfL">https://bit.ly/3NfTRfL</a></p>
            <p>20) <strong>Rummer, J.L.</strong>, Heron, S.H. (2022) Adapt, move, or die: repeated coral bleaching leaves wildlife on the Great Barrier Reef with few options.<strong><em> The Conversation</em></strong>. 21 March 2022. <a href="https://bit.ly/3a6fsZl">https://bit.ly/3a6fsZl</a></p>
            <p>19) Cooke, S.J., Hultine, K.R., <strong>Rummer, J.L.</strong>, Fangue, N.A., Seebacher, F., Eliason, E.J., MacMillan,<br />H.A., Fuller, A. Fuller, Franklin, C.E. (2022). Elevating the impact of conservation physiology by<br />building a community devoted to excellence, transparency, ethics, integrity and mutual respect.<br /><strong><em>Conservation Physiology</em></strong>. 10(1), coac015. <a href="https://doi.org/10.1093/conphys/coac015">https://doi.org/10.1093/conphys/coac015</a><br />IF: 3.079, Citations: n/a, Altmetric: n/a</p>
            <p>18) <u>Wheeler, C.W.</u>, <strong>Rummer, J.L.</strong>, (2021) Walking sharks. <strong><em>Oceanographic</em></strong>. Issue 21, 102-109.</p>
            <p>17) <strong>Rummer, J.L.</strong>, <u>Weideli, O.C.</u> (2021) Sharks and climate change. <strong><em>Oceanographic</em></strong>. Issue 17, 84-93.</p>
            <p>16) Cooke, S.J., Cramp, R.L., Madliger, C.L., Bergman, J.N., Reeve, C., <strong>Rummer, J.L.</strong>, Hultine, K.R., Fuller, A., French, S.S., Franklin, C.E. (2021). Conservation physiology and the COVID-19 pandemic. <strong><em>Conservation Physiology </em></strong>9, coaa139. doi: <a href="https://doi.org/10.1093/conphys/coaa139">https://doi.org/10.1093/conphys/coaa139</a><br />IF: 3.079, Citations: n/a, Altmetric: 7</p>
            <p>15) <strong>Rummer, J.L.</strong>, Allan, B.J.M., Pattiaratchi, C., <u>Bouyoucos, I.A.</u>, Yulianto, I., van der Mheen, M. (2020). It might be the biggest world&rsquo;s biggest ocean, but the mighty Pacific is in peril. <strong><em>The Conversation</em></strong>. 6 December 2020. <a href="https://bit.ly/2YSwgK9">https://bit.ly/2YSwgK9</a></p>
            <p>14) <strong>Rummer, J.L. </strong>(2020) I studied what happens to coral reef fish after coral bleaching. What I saw still makes me nauseous. <strong><em>The Conversation</em></strong>. 27 March 2020. <a href="https://bit.ly/347my8K">https://bit.ly/347my8K</a></p>
            <p>13) Tomlinson, S., <strong>Rummer, J.L.</strong>, Hultine, K.R., Cooke, S.J. (2018) Crossing boundaries in conservation physiology. <strong><em>Conservation Physiology </em></strong>6 (1): coy015. doi: <a href="https://doi.org/10.1093/conphys/cox011">10.1093/conphys/coy015</a><br />IF: 3.079, Citations: n/a, Altmetric: 15</p>
            <p>12) <strong>Rummer, J.L. </strong>(2017) What if you can&rsquo;t sense your enemy&hellip; and your enemy is an invasive predator? <strong><em>Conservation Physiology </em></strong>5 (1): cox011. doi: <a href="https://doi.org/10.1093/conphys/cox011">10.1093/conphys/cox011</a><br />IF: 3.079, Citations: n/a, Altmetric: 44</p>
            <p>11) Cooke, S.J., Hultine, K.R., <strong>Rummer, J.L.</strong>, Franklin, C.E. (2017) Reflections and progress in conservation physiology. <strong><em>Conservation Physiology </em></strong>5(1), cow071. doi:&nbsp;10.1093/conphys/cow071<br />IF: 3.079, Citations: n/a, Altmetric: 5</p>
            <p>10) Reside, A.E., Bridge, T.C.L., <strong>Rummer, J.L. </strong>(2016) Great Barrier Reef: Clearing the way for reef destruction. <strong><em>Nature</em></strong> 537, 307-307. doi:10.1038/537307d<br />IF: 49.962, Citations: 2, Altmetric: 19</p>
            <p>9) <strong>Rummer, J.L.</strong> (2010) Communication skills for the biosciences: A graduate guide. <strong><em>The Quarterly Review of Biology</em></strong> 85, 488-489. doi:10.1086/656837<br />IF: 4.389, Citations: n/a, Altmetric: n/a</p>
            <p>8) <strong>Rummer, J.L.</strong> (2010) Is it cheaper to &ldquo;grow up&rdquo; fast? <strong><em>Journal of Experimental Biology</em></strong> 213: iv. doi:10.1242/jeb.036749<br />IF: 3.312, Citations: n/a, Altmetric: n/a</p>
            <p>7) <strong>Rummer, J.L.</strong> (2010) How wooly mammoth blood cheated the cold <strong><em>Journal of Experimental Biology</em></strong> 213: v. doi:10.1242/jeb.036624<br />IF: 3.312, Citations: n/a, Altmetric: n/a</p>
            <p>6) <strong>Rummer, J.L.</strong> (2010) Ionregulation drives gill development <strong><em>Journal of Experimental Biology</em></strong> 213:iv. doi:10.1242/jeb.036509<br />IF: 3.312, Citations: n/a, Altmetric: n/a</p>
            <p>5) <strong>Rummer, J.L. (</strong>2010. Brrrown adipose tissue: special fat for cold critters <strong><em>Journal of Experimental Biology</em></strong> 213: vi. doi:10.1242/jeb.036384<br />IF: 3.312, Citations: n/a, Altmetric: n/a</p>
            <p>4) <strong>Rummer, J.L. </strong>2009. Komodo dragon&rsquo;s &ldquo;pearly whites&rdquo; pack a 1-2-3 deadly punch <strong><em>Journal of Experimental Biology</em></strong> 212:iv. doi:10.1242/jeb.023788<br />IF: 3.312, Citations: n/a, Altmetric: n/a</p>
            <p>3) <strong>Rummer, J.L.</strong> 2009. The real taste of victory. <strong><em>Journal of Experimental Biology</em></strong> 212:iv. doi:10.1242/jeb.023796<br />IF: 3.312, Citations: n/a, Altmetric: n/a</p>
            <p>2) <strong>Rummer, J.L.</strong> 2009. Global warming could cancel &lsquo;journey of a thousand miles.&rsquo; <strong><em>Journal of Experimental Biology</em></strong> 212:v. doi:10.1242/jeb.023804<br />IF: 3.312, Citations: n/a, Altmetric: n/a</p>
            <p>1) <strong>Rummer, J.L.</strong> 2009. A little stress for a fetus goes a long way. <strong><em>Journal of Experimental Biology</em></strong> 212(4):v. doi:10.1242/jeb.023812<br />IF: 3.312, Citations: n/a, Altmetric: n/a
            </p>
            <p><br /><em>Fish drawings designed for Jodie Rummer by&nbsp;<a href="http://www.loggods.com/sci/index.php">Erin Walsh</a></em></p>
        </>
    )
}
